-- ============================================================================
-- Extracted SQL Statements from GadgetsOnline .NET EF6/LINQ Application
-- These are the equivalent MS SQL Server statements generated by EF6/LINQ at runtime
-- Total Logical Statements: 16
-- Total Physical Statements: 17 (Statement 11 has UPDATE and DELETE parts)
-- Source Database: MS SQL Server (dbo schema)
-- ============================================================================

-- Statement 1: Inventory.GetBestSellers (Services/Inventory.cs)
-- LINQ: _gadgetsOnlineEntities.Products.Take(count).ToList()
-- Description: Retrieves top N products as best sellers
SELECT TOP (@count) ProductId, CategoryId, Name, Price, ProductArtUrl FROM dbo.Products;

-- Statement 2: Inventory.GetAllCategories (Services/Inventory.cs)
-- LINQ: _gadgetsOnlineEntities.Categories.ToList()
-- Description: Retrieves all categories
SELECT CategoryId, Name, Description FROM dbo.Categories;

-- Statement 3: Inventory.GetAllProductsInCategory (Services/Inventory.cs)
-- LINQ: _gadgetsOnlineEntities.Products.Where(p => p.Category.Name == category).ToList()
-- Description: Retrieves all products in a specific category via JOIN
SELECT p.ProductId, p.CategoryId, p.Name, p.Price, p.ProductArtUrl FROM dbo.Products p INNER JOIN dbo.Categories c ON p.CategoryId = c.CategoryId WHERE c.Name = @category;

-- Statement 4: Inventory.GetProductById (Services/Inventory.cs)
-- LINQ: _gadgetsOnlineEntities.Products.Where(p => p.ProductId == id).FirstOrDefault()
-- Description: Retrieves a single product by its ID
SELECT ProductId, CategoryId, Name, Price, ProductArtUrl FROM dbo.Products WHERE ProductId = @id;

-- Statement 5: Inventory.GetProductNameById (Services/Inventory.cs)
-- LINQ: _gadgetsOnlineEntities.Products.Where(p => p.ProductId == id).FirstOrDefault().Name
-- Description: Retrieves only the product name by its ID
SELECT Name FROM dbo.Products WHERE ProductId = @id;

-- Statement 6: ShoppingCart.AddToCart - SELECT (Services/ShoppingCart.cs)
-- LINQ: _gadgetsOnlineEntities.Carts.SingleOrDefault(c => c.CartId == ShoppingCartId && c.ProductId == id)
-- Description: Checks if a product already exists in the cart
SELECT RecordId, CartId, ProductId, Count, DateCreated FROM dbo.Carts WHERE CartId = @cartId AND ProductId = @productId;

-- Statement 7: ShoppingCart.AddToCart - INSERT (Services/ShoppingCart.cs)
-- LINQ: _gadgetsOnlineEntities.Carts.Add(cartItem) where cartItem = new Cart{...DateCreated = DateTime.Now}
-- Description: Adds a new item to the cart
INSERT INTO dbo.Carts (CartId, ProductId, Count, DateCreated) VALUES (@cartId, @productId, 1, GETDATE());

-- Statement 8: ShoppingCart.GetCount (Services/ShoppingCart.cs)
-- LINQ: (from cartItems in _gadgetsOnlineEntities.Carts where cartItems.CartId == ShoppingCartId select (int?)cartItems.Count).Sum()
-- Description: Gets the total count of items in the cart
SELECT ISNULL(SUM(Count), 0) FROM dbo.Carts WHERE CartId = @cartId;

-- Statement 9: ShoppingCart.GetCartItems (Services/ShoppingCart.cs)
-- LINQ: _gadgetsOnlineEntities.Carts.Where(cart => cart.CartId == ShoppingCartId).ToList()
-- Description: Retrieves all items in the cart
SELECT RecordId, CartId, ProductId, Count, DateCreated FROM dbo.Carts WHERE CartId = @cartId;

-- Statement 10: ShoppingCart.GetTotal (Services/ShoppingCart.cs)
-- LINQ: (from cartItems in _gadgetsOnlineEntities.Carts where cartItems.CartId == ShoppingCartId select (int?)cartItems.Count * cartItems.Product.Price).Sum()
-- Description: Calculates the total price of all items in the cart
SELECT ISNULL(SUM(c.Count * p.Price), 0) FROM dbo.Carts c INNER JOIN dbo.Products p ON c.ProductId = p.ProductId WHERE c.CartId = @cartId;

-- Statement 11a: ShoppingCart.RemoveFromCart - UPDATE (Services/ShoppingCart.cs)
-- LINQ: cartItem.Count-- then SaveChanges (when count > 1)
-- Description: Decrements item count in cart
UPDATE dbo.Carts SET Count = Count - 1 WHERE CartId = @cartId AND ProductId = @productId;

-- Statement 11b: ShoppingCart.RemoveFromCart - DELETE (Services/ShoppingCart.cs)
-- LINQ: _gadgetsOnlineEntities.Carts.Remove(cartItem) (when count <= 1)
-- Description: Removes item from cart
DELETE FROM dbo.Carts WHERE CartId = @cartId AND ProductId = @productId;

-- Statement 12: ShoppingCart.EmptyCart (Services/ShoppingCart.cs)
-- LINQ: foreach cartItem in query: _gadgetsOnlineEntities.Carts.Remove(cartItem)
-- Description: Removes all items from the cart
DELETE FROM dbo.Carts WHERE CartId = @cartId;

-- Statement 13: ShoppingCart.CreateOrder - INSERT OrderDetails (Services/ShoppingCart.cs)
-- LINQ: _gadgetsOnlineEntities.OrderDetails.Add(orderDetail) in foreach loop
-- Description: Inserts order detail records for each cart item
INSERT INTO dbo.OrderDetails (OrderId, ProductId, Quantity, UnitPrice) VALUES (@orderId, @productId, @quantity, @unitPrice);

-- Statement 14: OrderProcessing.ProcessOrder - INSERT Orders (Services/OrderProcessing.cs)
-- LINQ: _gadgetsOnlineEntities.Orders.Add(order)
-- Description: Inserts a new order record
INSERT INTO dbo.Orders (OrderDate, Username, FirstName, LastName, Address, City, State, PostalCode, Country, Phone, Email, Total) VALUES (@orderDate, @username, @firstName, @lastName, @address, @city, @state, @postalCode, @country, @phone, @email, @total);

-- Statement 15: GadgetsOnlineInitializer.Seed - INSERT Categories (Models/GadgetsOnlineInitializer.cs)
-- LINQ: categories.ForEach(c => context.Categories.Add(c))
-- Description: Seeds initial category data
INSERT INTO dbo.Categories (CategoryId, Name, Description) VALUES (@categoryId, @name, @description);

-- Statement 16: GadgetsOnlineInitializer.Seed - INSERT Products (Models/GadgetsOnlineInitializer.cs)
-- LINQ: products.ForEach(p => context.Products.Add(p))
-- Description: Seeds initial product data
INSERT INTO dbo.Products (ProductId, CategoryId, Name, Price, ProductArtUrl) VALUES (@productId, @categoryId, @name, @price, @productArtUrl);
